//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lluviaBackEnd.servicioTimbradoProductivo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:respuestaTimbrado", ConfigurationName="servicioTimbradoProductivo.timbrarCFDIPortType")]
    public interface timbrarCFDIPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.edifactmx-pac.com/serviceCFDI/timbraCFDI.php/timbrarCFDI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        lluviaBackEnd.servicioTimbradoProductivo.respuestaTimbrado timbrarCFDI(string suscriptorRFC, string agenteTI, string documentoXML);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.edifactmx-pac.com/serviceCFDI/timbraCFDI.php/timbrarCFDI", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<lluviaBackEnd.servicioTimbradoProductivo.respuestaTimbrado> timbrarCFDIAsync(string suscriptorRFC, string agenteTI, string documentoXML);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:respuestaTimbrado")]
    public partial class respuestaTimbrado : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentoTimbradoField;
        
        private string codigoResultadoField;
        
        private string codigoDescripcionField;
        
        /// <remarks/>
        public string documentoTimbrado {
            get {
                return this.documentoTimbradoField;
            }
            set {
                this.documentoTimbradoField = value;
                this.RaisePropertyChanged("documentoTimbrado");
            }
        }
        
        /// <remarks/>
        public string codigoResultado {
            get {
                return this.codigoResultadoField;
            }
            set {
                this.codigoResultadoField = value;
                this.RaisePropertyChanged("codigoResultado");
            }
        }
        
        /// <remarks/>
        public string codigoDescripcion {
            get {
                return this.codigoDescripcionField;
            }
            set {
                this.codigoDescripcionField = value;
                this.RaisePropertyChanged("codigoDescripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface timbrarCFDIPortTypeChannel : lluviaBackEnd.servicioTimbradoProductivo.timbrarCFDIPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class timbrarCFDIPortTypeClient : System.ServiceModel.ClientBase<lluviaBackEnd.servicioTimbradoProductivo.timbrarCFDIPortType>, lluviaBackEnd.servicioTimbradoProductivo.timbrarCFDIPortType {
        
        public timbrarCFDIPortTypeClient() {
        }
        
        public timbrarCFDIPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public timbrarCFDIPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public timbrarCFDIPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public timbrarCFDIPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public lluviaBackEnd.servicioTimbradoProductivo.respuestaTimbrado timbrarCFDI(string suscriptorRFC, string agenteTI, string documentoXML) {
            return base.Channel.timbrarCFDI(suscriptorRFC, agenteTI, documentoXML);
        }
        
        public System.Threading.Tasks.Task<lluviaBackEnd.servicioTimbradoProductivo.respuestaTimbrado> timbrarCFDIAsync(string suscriptorRFC, string agenteTI, string documentoXML) {
            return base.Channel.timbrarCFDIAsync(suscriptorRFC, agenteTI, documentoXML);
        }
    }
}
