

begin tran

exec SP_GUARDA_PEDIDO_ESPECIAL_V2
@xml =N'<ArrayOfProducto>
  <Producto>
    <idProducto>696</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>1.5</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>3</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>1493</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>6</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>84</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>3</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>3</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>131</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>4</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>409</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>2</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>110</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>6</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>109</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>6</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>331</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>10</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>601</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>30</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>593</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>20</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>588</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>10</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>508</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>10</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>424</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>4</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
  <Producto>
    <idProducto>488</idProducto>
    <cantidadUnidadMedida>0</cantidadUnidadMedida>
    <activo>false</activo>
    <cantidad>6</cantidad>
    <fechaAlta>0001-01-01T00:00:00</fechaAlta>
    <fechaIni>0001-01-01T00:00:00</fechaIni>
    <fechaFin>0001-01-01T00:00:00</fechaFin>
    <contador>0</contador>
    <precioIndividual>0</precioIndividual>
    <precioMenudeo>0</precioMenudeo>
    <precio>0</precio>
    <idPasillo>0</idPasillo>
    <idRaq>0</idRaq>
    <idPiso>0</idPiso>
    <idAlmacen>4</idAlmacen>
    <idSucursal>0</idSucursal>
    <idUsuario>0</idUsuario>
    <costo>0</costo>
    <total>0</total>
    <estatusProducto>
      <idEstatusProducto>0</idEstatusProducto>
    </estatusProducto>
    <cantidadRecibida>0</cantidadRecibida>
    <cantidadDevuelta>0</cantidadDevuelta>
    <porcUtilidadIndividual>0</porcUtilidadIndividual>
    <porcUtilidadMayoreo>0</porcUtilidadMayoreo>
    <unidadCompra>
      <idUnidadCompra>0</idUnidadCompra>
      <cantidadUnidadCompra>0</cantidadUnidadCompra>
    </unidadCompra>
    <fraccion>false</fraccion>
    <idUbicacion>0</idUbicacion>
    <ultimoCostoCompra>0</ultimoCostoCompra>
    <idPedidoEspecialDetalle>0</idPedidoEspecialDetalle>
    <idPedidoEspecial>0</idPedidoEspecial>
    <idVenta>0</idVenta>
    <idAlmacenOrigen>0</idAlmacenOrigen>
    <idAlmacenDestino>0</idAlmacenDestino>
    <cantidadActualInvGeneral>0</cantidadActualInvGeneral>
    <cantidadAnteriorInvGeneral>0</cantidadAnteriorInvGeneral>
    <cantidadActualInvAlmacen>0</cantidadActualInvAlmacen>
    <precioVenta>0</precioVenta>
    <cantidadSolicitada>0</cantidadSolicitada>
    <cantidadAtendida>0</cantidadAtendida>
    <cantidadAceptada>0</cantidadAceptada>
    <cantidadRechazada>0</cantidadRechazada>
    <idTicketMayoreo>0</idTicketMayoreo>
    <idUsuarioRuteo>0</idUsuarioRuteo>
    <idEstatusPedidoEspecialDetalle>0</idEstatusPedidoEspecialDetalle>
    <id>0</id>
  </Producto>
</ArrayOfProducto>'
,@tipoRevision =1
,@idCliente =1
,@idUsuario =9
,@idEstatusPedidoEspecial =1
,@idEstacion = 1
,@idPedidoEspecial =0
,@idPedidoEspecialMayoreo_ =0
--select * from InventarioDetalleLog where  idProducto = 84 order by fechaAlta desc
--select * from InventarioDetalleLog order by fechaAlta desc
--select top 100 * from PedidosEspecialesDetalle  order by fechaAlta desc
rollback tran 


--select * from InventarioDetalle ID join Ubicacion u on ID.idUbicacion = u.idUbicacion  where idProducto = 84

